### ISSUE TITLE
.eventually assertion doesn't fail when Error message mismatch.

### ISSUE THREAD

**Issue by toymachiner62** [chaijs/chai-as-promised#277]
This test passes and I don't think it should.

Shouldn't this test fail due to `myErrorMessage` not being equal to `my error message`?

```js
const chai = require('chai');
const expect = chai.expect;
const chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);

describe('eventually throw does not work with an error message', () => {

    it('should fail because the message does not match', () => {
        expect(throwError()).to.eventually.throw(Error, 'myErrorMessage')
    });
});

async function throwError() {
    throw new Error('my error message');
}
```

**Comment by SmashingQuasar** [comment]
Can confirm that it ignores the error message, even when trying the different possible approaches (RegExp, string, etc.).

**Comment by 43081j** [comment]
i think this is expected behaviour as you should use `rejectedWith` in these situations

for example:

```ts
expect(throwError()).to.be.rejectedWith(Error, 'myErrorMessage');
```

generally you would only use `eventually` chains to assert against the eventual value (i.e. the resolved value)
