### ISSUE TITLE
Chai v5 support

### ISSUE THREAD

**Issue by meyfa** [chaijs/chai-as-promised#281]
The current peerDependencies version range forbids installing chai-as-promised with chai v5:

```
"peerDependencies": {
    "chai": ">= 2.1.2 < 5"
  }
```

Release notes: https://github.com/chaijs/chai/releases/tag/v5.0.0

**Comment by Stwissel** [comment]
I have the problem too. @domenic -> if you have no bandwidth to maintain, let's talk

**Comment by BryanHuntNV** [comment]
Also note that chai.use() doesn't currently work without a code change: https://github.com/chaijs/chai/issues/1569

**Comment by MirzaMBaig** [comment]
node version - v16.19.1
npm version - 8.19.3

when updated the package dependencies for chai to 5.0.0 its not longer working. 

```
npm WARN While resolving: service-client-js@4.3.0-SNAPSHOT
npm WARN Found: chai@4.3.10
npm WARN node_modules/chai
npm WARN   dev chai@"^5.0.0" from the root project
npm WARN   1 more (chai-as-promised)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer chai@">= 2.1.2 < 5" from chai-as-promised@7.1.1
npm WARN node_modules/chai-as-promised
npm WARN   dev chai-as-promised@"^7.1.1" from the root project
```

**Comment by mcm1957** [comment]
Chai 5 is DEFINITLY not useable currently

**Comment by BryanHuntNV** [comment]
See also: https://github.com/chaijs/chai/issues/1570

**Comment by khteh** [comment]
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: node.jsrestapi@1.0.0
npm ERR! Found: chai@5.0.0
npm ERR! node_modules/chai
npm ERR!   dev chai@"^5.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer chai@">= 2.1.2 < 5" from chai-as-promised@7.1.1
npm ERR! node_modules/chai-as-promised
npm ERR!   dev chai-as-promised@"^7.1.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/khteh/.npm/_logs/2024-01-06T09_00_12_017Z-eresolve-report.txt
```

**Comment by mcm1957** [comment]
Hope you noticed that the last commit at this repository is 6 years ago.
I would not expect a fast fix...

**Comment by khteh** [comment]
Is there any alternative to this library?

**Comment by mcm1957** [comment]
> Is there any alternative to this library?

https://github.com/chaijs/chai/issues/1570

**Comment by rvagg** [comment]
I got desperate enough to fork and fix, https://github.com/rvagg/chai-as-promised, `@rvagg/chai-as-promised` is ESM, bundles the `@types/chai-as-promised` types, and works with chai@5. Can upstream some of those commits here if Domenic decides this isn't a dead project.

**Comment by euberdeveloper** [comment]
> I got desperate enough to fork and fix, https://github.com/rvagg/chai-as-promised, `@rvagg/chai-as-promised` is ESM, bundles the `@types/chai-as-promised` types, and works with chai@5. Can upstream some of those commits here if Domenic decides this isn't a dead project.

Just in time

**Comment by KaiSchwarz-cnic** [comment]
As long as there are no breaking changes somewhere, you can simply add `chai` to package.json's `overrides` section e.g.:

```
...
  "overrides": {
    "chai": "^5.0.0"
  },
...
```

This approach is giving us often a bit time for either finding a maintained replacement or forking + maintaining on our own or for entirely cleaning up an unmaintained dependency. More freedom temporarily ...

**Comment by ramanarupa** [comment]
https://github.com/ramanarupa/chai-promised

**Comment by 43081j** [comment]
FYI 7.1.2 resolves the peer dependency issue

8.0.0 is on the way and will be esm-only like chai itself

closing since the 7.1.2 release should solve this issue for now.
