### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by GustavoOS** [chaijs/chai-as-promised#288]
The last accepted commit is now 6 years old.
Chai-as-promised doesn't yet support chai 5 (current version) and there isn't a single contributor answering #281

**Comment by GustavoOS** [comment]
@domenic would you please deprecate if an affirmative answer?

**Comment by WikiRik** [comment]
Actually, this repo was moved to the chai organisation earlier this week. With their help there should be a reboot in maintenance for this package, including chai v5 support. You can already see some of the PRs they have opened that will be merged soon

**Comment by 43081j** [comment]
Indeed it did! I'll be merging a bunch of prs and doing some releases this week 👍

I'm also investigating adding async support to chai core one day
