### ISSUE TITLE
ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by khteh** [chaijs/chai-as-promised#298]
`package.json`:
```
  "devDependencies": {
    "@types/chai-as-promised": "^7.1.8",
    "@types/jest": "^29.5.12",
    "@types/mocha": "^10.0.6",
    "chai": "^5.1.1",
    "chai-http": "^4.4.0",
}
```
```
$ n i -D chai-as-promised
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: node.jsrestapi@1.0.0
npm error Found: chai@5.1.1
npm error node_modules/chai
npm error   dev chai@"^5.1.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer chai@">= 2.1.2 < 5" from chai-as-promised@7.1.1
npm error node_modules/chai-as-promised
npm error   dev chai-as-promised@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/khteh/.npm/_logs/2024-06-01T06_38_53_953Z-eresolve-report.txt
npm error A complete log of this run can be found in: /home/khteh/.npm/_logs/2024-06-01T06_38_53_953Z-debug-0.log
```

**Comment by 43081j** [comment]
The latest 7.x version should resolve this already

Try upgrading chai-as-promised

**Comment by khteh** [comment]
Don't you see `"@types/chai-as-promised": "^7.1.8",` and `npm error peer chai@">= 2.1.2 < 5" from chai-as-promised@7.1.1
` in my post?

**Comment by 43081j** [comment]
i see it

```
npm error peer chai@">= 2.1.2 < 5" from chai-as-promised@7.1.1
```

but i published a new version of chai-as-promised a week or two ago that changes this range to `< 6` instead of `< 5`

you can see that in 7.1.2:
https://unpkg.com/browse/chai-as-promised@7.1.2/package.json

your `devDependencies` also doesn't have `chai-as-promised` but does have the types, maybe that needs fixing?

**Comment by khteh** [comment]
I was trying to `npm i -D chai-as-promised` and hit this error and therefore this issue created!

**Comment by 43081j** [comment]
that seems strange as its trying to install `7.1.1` which certainly will error with chai 5

you need `7.1.2`, which is the latest version:
https://www.npmjs.com/package/chai-as-promised/v/7.1.2

im surprised `npm i` didn't pull that one in 🤔  its definitely the `latest` version on npm

**Comment by khteh** [comment]
Managed to install successfully today. Thanks!
