### ISSUE TITLE
NPM still lists WTFPL license

### ISSUE THREAD

**Issue by mjsalinger** [chaijs/chai-as-promised#303]
The NPM registry still lists this package as falling under the WTFPL license even though it's changed to MIT.  Can you publish the last update so it reflects on the npm registry?

**Comment by 43081j** [comment]
Good catch 👍

I'll see if I can update in the next few days unless someone beats me to it

**Comment by 43081j** [comment]
Should be fixed by 8.0.1

**Comment by mjsalinger** [comment]
Thanks for the quick turnaround!  Was doing a license audit for work and noticed this discrepancy.  Appreciate it!
