### ISSUE TITLE
Chai-As-Promised is eating assertion errors

### ISSUE THREAD

**Issue by kumarharsh** [chaijs/chai-as-promised#40]
I'm using **chai-as-promised** + **mocha** for writing some **selenium-webdriver** tests. Since webdriver extensively uses **promises**, I imagined it would be better if I used chai-as-promised for those type of tests.

The problem is that when the tests fail, the error is not being caught properly by mocha, and it just fails without outputting anything.

Sample code:

``` coffee-script
it 'tests log', (next) ->
  log = @client.findElement(By.css("..."))
  Q.all([
    expect(log.getText()).to.eventually.equal("My Text")
    expect(log.findElement(By.css(".image")).getAttribute('src'))
      .to.eventually.equal("/test.png")
  ]).should.notify(next)
```

According to [documented behaviour](https://github.com/domenic/chai-as-promised/#working-with-non-promisefriendly-test-runners), **chai-as-promised** should pass the errors along to mocha when the expectation fails. Right?

As a variation,

I've also tried these, but to no avail:

2nd Try  (same, no error on failure)

``` coffee-script
it 'tests log', (next) ->
  log = @client.findElement(By.css("..."))
  Q.all([
    expect(log.getText()).to.eventually.equal("My Text")
    expect(log.findElement(By.css(".image")).getAttribute('src'))
      .to.eventually.equal("/test.png")
  ]).should.notify(next)
```

3rd Try (same, no error shown on failure)

``` coffee-script
it 'tests log', (next) ->
  log = @client.findElement(By.css("..."))
  expect(log.getText()).to.eventually.equal("My Text")
  .then ->
     expect(log.findElement(By.css(".image")).getAttribute('src'))
       .to.eventually.equal("/test.png").should.notify(next)
```

4th try (DOES NOT EVEN PASS)

``` coffee-script
it 'tests log', (next) ->            
  log = @client.findElement(By.css("..."))
  Q.all([
    expect(log.getText()).to.eventually.equal("My Text")
    expect(log.findElement(By.css(".image")).getAttribute('src'))
      .to.eventually.equal("/test.png")
  ])
  .then ->
    next()
  .fail (err) ->
    console.log(err)
  .done()
```

---

Right now, I'm using this to show the assertion errors. It's a nasty looking workaround. Can you please help?

``` coffee-script
it 'tests log', (next) ->
  log = @client.findElement(By.css("..."))
  Q.all([
    expect(log.getText()).to.eventually.equal("My Text")
    expect(log.findElement(By.css(".image")).getAttribute('src'))
      .to.eventually.equal("/test.png")
  ]).should.notify((err) ->
      console.log err if err   # <-- this line does the trick
      next(err)
  )
```

**Comment by johnelm** [comment]
@domenic I'm just getting started with chai-as-promised for my WebDriverJS project.  @kumarharsh where did you land with this?  Did you have to stop using chai-as-promised for your webdriver stuff?
