### ISSUE TITLE
promise on the right side

### ISSUE THREAD

**Issue by indeyets** [chaijs/chai-as-promised#67]
is there any proper way of comparing results of 2 promises? we use chai-as-promised for acceptance testing and have a use-case, where we need to compare values of 2 different calls (relative positioning of dom-elements, etc.)

We would like to do something like:

``` javascript
expect(promise1).eventually.to.equal(promise2).and.notify(next);
```

this one doesn't work for obvious reasons. right now we wrap expecation in a closure and manually get result of promise2. can we avoid it?

**Comment by Visya** [comment]
+1 for this request. I'd really like to write simple
```js
expect(promise1).to.equal(promise2);
```

Maybe you can expose arguments modifier, so that users will be able to override it with chosen method? Something like this:

https://github.com/domenic/chai-as-promised/blob/master/lib/chai-as-promised.js#L303

```diff
--- chai-as-promised.js	Tue Feb 10 12:55:31 2015
+++ chai-as-promised.js.new	Tue Feb 10 12:54:31 2015
@@ -25,6 +26,10 @@
         assertion.then = promise.then.bind(promise);
     };
 
+    chaiAsPromised.flattenArguments = function (args) {
+        return args;
+    };
+
     function chaiAsPromised(chai, utils) {
         var Assertion = chai.Assertion;
         var assert = chai.assert;
@@ -299,6 +304,9 @@
                 // just the base Chai code that we get to via the short-circuit above.
                 assertion._obj = value;
                 utils.flag(assertion, "eventually", false);
+
+                return chaiAsPromised.flattenArguments(args);
+            }).then(function(args) {
                 asserter.apply(assertion, args);
 
                 // Because asserters, for example `property`, can change the value of `_obj` (i.e. change the "object"

```

Then, I can use it like this:
```js
chai.use(chaiAsPromise);
chaiAsPromise.flattenArguments = function(args) {
  return args ? q.all(args) : [];
};
```

**Comment by stalniy** [comment]
+1 for merging this patch

**Comment by domenic** [comment]
Unfortunately I have a policy that every time someone adds a comment with no content but instead just a "+1", I have to delay looking at the thread for a week for every such comment. So, I'll come back to this thread in a week.

**Comment by YuriSolovyov** [comment]
@domenic but this one had a content :)

**Comment by stalniy** [comment]
@domenic will you be satisfied if @Visya or me create a pull request with tests for this change?
