### ISSUE TITLE
Does not work with other plugins when chai loaded multiple times

### ISSUE THREAD

**Issue by jreichenberg** [chaijs/chai-as-promised#70]
Hi,

I've created my own chai plugin with custom assertions. In order to get it working with chai-as-promised I found I needed to load my custom plugin first in my test spec (Mocha via NodeJs) and then chai-as-promised:

```
var chai = require('chai'),
    myCustomAssertions = require('...');

chai.use(myCustomAssertions);
chai.use(require('chai-as-promised'));
```

The above works fine if its the only spec running.  If I switch the order of the `use` statements then chai-as-promised does not hook my custom assertions and they get fed unresolved promises.

The problem is that if I load multiple spec files, and the ones loaded first use chai-as-promised but not my custom assertions, then `chai.use()` does nothing as the chai-as-promised library has already done its stuff and my custom assertions are no longer hooked and modified by chai-as-promised.

Spec 1 in Node/Mocha process:

```
var chai = require('chai');
chai.use(require('chai-as-promised'));
```

Spec 2 in same Node/Mocha process:

```
var chai = require('chai'),
    myCustomAssertions = require('...');

chai.use(myCustomAssertions);
chai.use(require('chai-as-promised'));
```

Suggestions?  Make sense?

**Comment by Atlas7** [comment]
`chai.use` plugin newbie here. Say if I want to use the following two plugins together, is that possible / discouraged?

```
chai.use(chaiAsPromised)
chai.use(chaiImmutable)
```

I haven't really tried it yet but on top of my mind what if in a `Mocha` test, we have async functions (that requires `chaiAsPromised`), and immutable data structures (that requires `chaiImmutable`)?

Apologies if this question sounds very dumb - in advance!
